layout_spectrum: 0.5752688
typography_spectrum: 0.4229391
color:
  saturation: 0.4815295
  lightness: 0.7455197
  brandStrength: 0.9910395
  brandColors:
    - '#ADAAA5'
    - '#494553'
    - '#09060D'
    - '#E5D6B9'
    - '#946F33'
  rhythmicContrast: 0.7060932
name: www.louvex.com
